#############################################################################
# Makefile for building: bin/it4kids-editor
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  GUI.pro
# Template: app
# Command: /usr/lib/qt/bin/qmake -o Makefile GUI.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -Isrc -isystem /usr/include/python2.7 -isystem /usr/include/qt -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtCore -Igenerated -I. -I/usr/lib/qt/mkspecs/linux-g++
QMAKE         = /usr/lib/qt/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = it4kids-editor1.0.0
DISTDIR = /home/stes/code/it4kids/generated/it4kids-editor1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-O1,--sort-common,--as-needed,-z,relro
LIBS          = $(SUBLIBS) -lpython2.7 -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = generated/

####### Files

SOURCES       = src/main.cpp \
		src/mainwindow.cpp \
		src/scene.cpp \
		src/categoryselect.cpp \
		src/dragableelement.cpp \
		src/dragelemcategory.cpp \
		src/dragelemlist.cpp \
		src/scriptarea.cpp \
		src/hatde.cpp \
		src/commandde.cpp \
		src/wrapperde.cpp \
		src/predicatede.cpp \
		src/paramdock.cpp \
		src/paramnumber.cpp \
		src/paramstring.cpp \
		src/paramdirection.cpp \
		src/paramdestination.cpp \
		src/paramkey.cpp \
		src/paraminteraction.cpp \
		src/parammessage.cpp \
		src/paramstopchoices.cpp \
		src/paramclone.cpp \
		src/paramcostume.cpp \
		src/parameffect.cpp \
		src/paramtouch.cpp \
		src/paramcolor.cpp \
		src/paramsound.cpp \
		src/reporterde.cpp \
		src/parammath.cpp \
		src/paramjoinwords.cpp \
		src/paramtype.cpp \
		src/paramdelim.cpp \
		src/paramvariables.cpp \
		src/paramlistselec.cpp \
		src/paramlistid.cpp \
		src/dockingarea.cpp \
		src/scriptdock.cpp \
		src/spriteselect.cpp \
		src/sprite.cpp qrc_resources.cpp \
		generated/moc_mainwindow.cpp \
		generated/moc_scene.cpp \
		generated/moc_categoryselect.cpp \
		generated/moc_dragableelement.cpp \
		generated/moc_dragelemcategory.cpp \
		generated/moc_dragelemlist.cpp \
		generated/moc_scriptarea.cpp \
		generated/moc_hatde.cpp \
		generated/moc_commandde.cpp \
		generated/moc_wrapperde.cpp \
		generated/moc_predicatede.cpp \
		generated/moc_paramdock.cpp \
		generated/moc_paramnumber.cpp \
		generated/moc_paramstring.cpp \
		generated/moc_paramdirection.cpp \
		generated/moc_paramdestination.cpp \
		generated/moc_paramkey.cpp \
		generated/moc_paraminteraction.cpp \
		generated/moc_parammessage.cpp \
		generated/moc_paramstopchoices.cpp \
		generated/moc_paramclone.cpp \
		generated/moc_paramcostume.cpp \
		generated/moc_parameffect.cpp \
		generated/moc_paramtouch.cpp \
		generated/moc_paramcolor.cpp \
		generated/moc_paramsound.cpp \
		generated/moc_reporterde.cpp \
		generated/moc_parammath.cpp \
		generated/moc_paramjoinwords.cpp \
		generated/moc_paramtype.cpp \
		generated/moc_paramdelim.cpp \
		generated/moc_paramvariables.cpp \
		generated/moc_paramlistselec.cpp \
		generated/moc_paramlistid.cpp \
		generated/moc_spriteselect.cpp \
		generated/moc_sprite.cpp
OBJECTS       = generated/main.o \
		generated/mainwindow.o \
		generated/scene.o \
		generated/categoryselect.o \
		generated/dragableelement.o \
		generated/dragelemcategory.o \
		generated/dragelemlist.o \
		generated/scriptarea.o \
		generated/hatde.o \
		generated/commandde.o \
		generated/wrapperde.o \
		generated/predicatede.o \
		generated/paramdock.o \
		generated/paramnumber.o \
		generated/paramstring.o \
		generated/paramdirection.o \
		generated/paramdestination.o \
		generated/paramkey.o \
		generated/paraminteraction.o \
		generated/parammessage.o \
		generated/paramstopchoices.o \
		generated/paramclone.o \
		generated/paramcostume.o \
		generated/parameffect.o \
		generated/paramtouch.o \
		generated/paramcolor.o \
		generated/paramsound.o \
		generated/reporterde.o \
		generated/parammath.o \
		generated/paramjoinwords.o \
		generated/paramtype.o \
		generated/paramdelim.o \
		generated/paramvariables.o \
		generated/paramlistselec.o \
		generated/paramlistid.o \
		generated/dockingarea.o \
		generated/scriptdock.o \
		generated/spriteselect.o \
		generated/sprite.o \
		generated/qrc_resources.o \
		generated/moc_mainwindow.o \
		generated/moc_scene.o \
		generated/moc_categoryselect.o \
		generated/moc_dragableelement.o \
		generated/moc_dragelemcategory.o \
		generated/moc_dragelemlist.o \
		generated/moc_scriptarea.o \
		generated/moc_hatde.o \
		generated/moc_commandde.o \
		generated/moc_wrapperde.o \
		generated/moc_predicatede.o \
		generated/moc_paramdock.o \
		generated/moc_paramnumber.o \
		generated/moc_paramstring.o \
		generated/moc_paramdirection.o \
		generated/moc_paramdestination.o \
		generated/moc_paramkey.o \
		generated/moc_paraminteraction.o \
		generated/moc_parammessage.o \
		generated/moc_paramstopchoices.o \
		generated/moc_paramclone.o \
		generated/moc_paramcostume.o \
		generated/moc_parameffect.o \
		generated/moc_paramtouch.o \
		generated/moc_paramcolor.o \
		generated/moc_paramsound.o \
		generated/moc_reporterde.o \
		generated/moc_parammath.o \
		generated/moc_paramjoinwords.o \
		generated/moc_paramtype.o \
		generated/moc_paramdelim.o \
		generated/moc_paramvariables.o \
		generated/moc_paramlistselec.o \
		generated/moc_paramlistid.o \
		generated/moc_spriteselect.o \
		generated/moc_sprite.o
DIST          = /usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/sanitize.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_declarative.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_declarative_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_ModemManagerQt.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/link_pkgconfig.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt/mkspecs/features/uic.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		GUI.pro src/mainwindow.h \
		src/scene.h \
		src/categoryselect.h \
		src/dragableelement.h \
		src/dragelemcategory.h \
		src/dragelemlist.h \
		src/scriptarea.h \
		src/hatde.h \
		src/commandde.h \
		src/wrapperde.h \
		src/predicatede.h \
		src/paramdock.h \
		src/paramnumber.h \
		src/param.h \
		src/paramstring.h \
		src/paramdirection.h \
		src/paramdestination.h \
		src/paramkey.h \
		src/paraminteraction.h \
		src/parammessage.h \
		src/paramstopchoices.h \
		src/paramclone.h \
		src/paramcostume.h \
		src/parameffect.h \
		src/paramtouch.h \
		src/paramcolor.h \
		src/paramsound.h \
		src/reporterde.h \
		src/parammath.h \
		src/paramjoinwords.h \
		src/paramtype.h \
		src/paramdelim.h \
		src/paramvariables.h \
		src/paramlistselec.h \
		src/paramlistid.h \
		src/dockingarea.h \
		src/scriptdock.h \
		src/spriteselect.h \
		src/sprite.h src/main.cpp \
		src/mainwindow.cpp \
		src/scene.cpp \
		src/categoryselect.cpp \
		src/dragableelement.cpp \
		src/dragelemcategory.cpp \
		src/dragelemlist.cpp \
		src/scriptarea.cpp \
		src/hatde.cpp \
		src/commandde.cpp \
		src/wrapperde.cpp \
		src/predicatede.cpp \
		src/paramdock.cpp \
		src/paramnumber.cpp \
		src/paramstring.cpp \
		src/paramdirection.cpp \
		src/paramdestination.cpp \
		src/paramkey.cpp \
		src/paraminteraction.cpp \
		src/parammessage.cpp \
		src/paramstopchoices.cpp \
		src/paramclone.cpp \
		src/paramcostume.cpp \
		src/parameffect.cpp \
		src/paramtouch.cpp \
		src/paramcolor.cpp \
		src/paramsound.cpp \
		src/reporterde.cpp \
		src/parammath.cpp \
		src/paramjoinwords.cpp \
		src/paramtype.cpp \
		src/paramdelim.cpp \
		src/paramvariables.cpp \
		src/paramlistselec.cpp \
		src/paramlistid.cpp \
		src/dockingarea.cpp \
		src/scriptdock.cpp \
		src/spriteselect.cpp \
		src/sprite.cpp
QMAKE_TARGET  = it4kids-editor
DESTDIR       = bin/#avoid trailing-slash linebreak
TARGET        = bin/it4kids-editor


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	@test -d bin/ || mkdir -p bin/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: GUI.pro /usr/lib/qt/mkspecs/linux-g++/qmake.conf /usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/sanitize.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_declarative.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_declarative_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_ModemManagerQt.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/link_pkgconfig.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt/mkspecs/features/uic.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		GUI.pro \
		src/resources.qrc \
		/usr/lib/libQt5Widgets.prl \
		/usr/lib/libQt5Gui.prl \
		/usr/lib/libQt5Core.prl
	$(QMAKE) -o Makefile GUI.pro
/usr/lib/qt/mkspecs/features/spec_pre.prf:
/usr/lib/qt/mkspecs/common/unix.conf:
/usr/lib/qt/mkspecs/common/linux.conf:
/usr/lib/qt/mkspecs/common/sanitize.conf:
/usr/lib/qt/mkspecs/common/gcc-base.conf:
/usr/lib/qt/mkspecs/common/gcc-base-unix.conf:
/usr/lib/qt/mkspecs/common/g++-base.conf:
/usr/lib/qt/mkspecs/common/g++-unix.conf:
/usr/lib/qt/mkspecs/qconfig.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_clucene_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_declarative.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_declarative_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_help.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_location.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_script.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkit_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/lib/qt/mkspecs/modules/qt_ModemManagerQt.pri:
/usr/lib/qt/mkspecs/features/qt_functions.prf:
/usr/lib/qt/mkspecs/features/qt_config.prf:
/usr/lib/qt/mkspecs/linux-g++/qmake.conf:
/usr/lib/qt/mkspecs/features/spec_post.prf:
/usr/lib/qt/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt/mkspecs/features/default_pre.prf:
/usr/lib/qt/mkspecs/features/resolve_config.prf:
/usr/lib/qt/mkspecs/features/default_post.prf:
/usr/lib/qt/mkspecs/features/link_pkgconfig.prf:
/usr/lib/qt/mkspecs/features/warn_on.prf:
/usr/lib/qt/mkspecs/features/qt.prf:
/usr/lib/qt/mkspecs/features/resources.prf:
/usr/lib/qt/mkspecs/features/moc.prf:
/usr/lib/qt/mkspecs/features/unix/opengl.prf:
/usr/lib/qt/mkspecs/features/uic.prf:
/usr/lib/qt/mkspecs/features/unix/thread.prf:
/usr/lib/qt/mkspecs/features/testcase_targets.prf:
/usr/lib/qt/mkspecs/features/exceptions.prf:
/usr/lib/qt/mkspecs/features/yacc.prf:
/usr/lib/qt/mkspecs/features/lex.prf:
GUI.pro:
src/resources.qrc:
/usr/lib/libQt5Widgets.prl:
/usr/lib/libQt5Gui.prl:
/usr/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile GUI.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents src/resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents src/mainwindow.h src/scene.h src/categoryselect.h src/dragableelement.h src/dragelemcategory.h src/dragelemlist.h src/scriptarea.h src/hatde.h src/commandde.h src/wrapperde.h src/predicatede.h src/paramdock.h src/paramnumber.h src/param.h src/paramstring.h src/paramdirection.h src/paramdestination.h src/paramkey.h src/paraminteraction.h src/parammessage.h src/paramstopchoices.h src/paramclone.h src/paramcostume.h src/parameffect.h src/paramtouch.h src/paramcolor.h src/paramsound.h src/reporterde.h src/parammath.h src/paramjoinwords.h src/paramtype.h src/paramdelim.h src/paramvariables.h src/paramlistselec.h src/paramlistid.h src/dockingarea.h src/scriptdock.h src/spriteselect.h src/sprite.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/mainwindow.cpp src/scene.cpp src/categoryselect.cpp src/dragableelement.cpp src/dragelemcategory.cpp src/dragelemlist.cpp src/scriptarea.cpp src/hatde.cpp src/commandde.cpp src/wrapperde.cpp src/predicatede.cpp src/paramdock.cpp src/paramnumber.cpp src/paramstring.cpp src/paramdirection.cpp src/paramdestination.cpp src/paramkey.cpp src/paraminteraction.cpp src/parammessage.cpp src/paramstopchoices.cpp src/paramclone.cpp src/paramcostume.cpp src/parameffect.cpp src/paramtouch.cpp src/paramcolor.cpp src/paramsound.cpp src/reporterde.cpp src/parammath.cpp src/paramjoinwords.cpp src/paramtype.cpp src/paramdelim.cpp src/paramvariables.cpp src/paramlistselec.cpp src/paramlistid.cpp src/dockingarea.cpp src/scriptdock.cpp src/spriteselect.cpp src/sprite.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

first: $(first) pythondata

pythondata:
	$(COPY_DIR) /home/stes/code/it4kids/src/python /home/stes/code/it4kids/bin/python

test:
	echo tests not yet implemented

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: src/resources.qrc \
		src/style.qss \
		src/blocks.xml \
		src/Assets/cameraOff.png \
		src/Assets/cameraOn.png \
		src/Assets/fullScreenOn.png \
		src/Assets/importOff.png \
		src/Assets/close.png \
		src/Assets/libraryOff.png \
		src/Assets/clockwise.png \
		src/Assets/greenFlagOn.png \
		src/Assets/landscapeOn.png \
		src/Assets/importOn.png \
		src/Assets/greenFlagOff.png \
		src/Assets/landscapeOff.png \
		src/Assets/stopOn.png \
		src/Assets/fullScreenOff.png \
		src/Assets/counterclockwise.png \
		src/Assets/paintbrushOff.png \
		src/Assets/stopOff.png \
		src/Assets/libraryOn.png \
		src/Assets/minimize.png \
		src/Assets/paintbrushOn.png
	/usr/lib/qt/bin/rcc -name resources src/resources.qrc -o qrc_resources.cpp

compiler_moc_header_make_all: generated/moc_mainwindow.cpp generated/moc_scene.cpp generated/moc_categoryselect.cpp generated/moc_dragableelement.cpp generated/moc_dragelemcategory.cpp generated/moc_dragelemlist.cpp generated/moc_scriptarea.cpp generated/moc_hatde.cpp generated/moc_commandde.cpp generated/moc_wrapperde.cpp generated/moc_predicatede.cpp generated/moc_paramdock.cpp generated/moc_paramnumber.cpp generated/moc_paramstring.cpp generated/moc_paramdirection.cpp generated/moc_paramdestination.cpp generated/moc_paramkey.cpp generated/moc_paraminteraction.cpp generated/moc_parammessage.cpp generated/moc_paramstopchoices.cpp generated/moc_paramclone.cpp generated/moc_paramcostume.cpp generated/moc_parameffect.cpp generated/moc_paramtouch.cpp generated/moc_paramcolor.cpp generated/moc_paramsound.cpp generated/moc_reporterde.cpp generated/moc_parammath.cpp generated/moc_paramjoinwords.cpp generated/moc_paramtype.cpp generated/moc_paramdelim.cpp generated/moc_paramvariables.cpp generated/moc_paramlistselec.cpp generated/moc_paramlistid.cpp generated/moc_spriteselect.cpp generated/moc_sprite.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) generated/moc_mainwindow.cpp generated/moc_scene.cpp generated/moc_categoryselect.cpp generated/moc_dragableelement.cpp generated/moc_dragelemcategory.cpp generated/moc_dragelemlist.cpp generated/moc_scriptarea.cpp generated/moc_hatde.cpp generated/moc_commandde.cpp generated/moc_wrapperde.cpp generated/moc_predicatede.cpp generated/moc_paramdock.cpp generated/moc_paramnumber.cpp generated/moc_paramstring.cpp generated/moc_paramdirection.cpp generated/moc_paramdestination.cpp generated/moc_paramkey.cpp generated/moc_paraminteraction.cpp generated/moc_parammessage.cpp generated/moc_paramstopchoices.cpp generated/moc_paramclone.cpp generated/moc_paramcostume.cpp generated/moc_parameffect.cpp generated/moc_paramtouch.cpp generated/moc_paramcolor.cpp generated/moc_paramsound.cpp generated/moc_reporterde.cpp generated/moc_parammath.cpp generated/moc_paramjoinwords.cpp generated/moc_paramtype.cpp generated/moc_paramdelim.cpp generated/moc_paramvariables.cpp generated/moc_paramlistselec.cpp generated/moc_paramlistid.cpp generated/moc_spriteselect.cpp generated/moc_sprite.cpp
generated/moc_mainwindow.cpp: src/mainwindow.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/stes/code/it4kids -I/home/stes/code/it4kids/src -I/usr/include/python2.7 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/5.2.0 -I/usr/include/c++/5.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include-fixed -I/usr/include src/mainwindow.h -o generated/moc_mainwindow.cpp

generated/moc_scene.cpp: src/scene.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/stes/code/it4kids -I/home/stes/code/it4kids/src -I/usr/include/python2.7 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/5.2.0 -I/usr/include/c++/5.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include-fixed -I/usr/include src/scene.h -o generated/moc_scene.cpp

generated/moc_categoryselect.cpp: src/dragelemcategory.h \
		src/mainwindow.h \
		src/dragableelement.h \
		src/scriptarea.h \
		src/scriptdock.h \
		src/dockingarea.h \
		src/dragelemlist.h \
		src/categoryselect.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/stes/code/it4kids -I/home/stes/code/it4kids/src -I/usr/include/python2.7 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/5.2.0 -I/usr/include/c++/5.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include-fixed -I/usr/include src/categoryselect.h -o generated/moc_categoryselect.cpp

generated/moc_dragableelement.cpp: src/scriptarea.h \
		src/scriptdock.h \
		src/dockingarea.h \
		src/dragableelement.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/stes/code/it4kids -I/home/stes/code/it4kids/src -I/usr/include/python2.7 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/5.2.0 -I/usr/include/c++/5.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include-fixed -I/usr/include src/dragableelement.h -o generated/moc_dragableelement.cpp

generated/moc_dragelemcategory.cpp: src/mainwindow.h \
		src/dragableelement.h \
		src/scriptarea.h \
		src/scriptdock.h \
		src/dockingarea.h \
		src/dragelemlist.h \
		src/dragelemcategory.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/stes/code/it4kids -I/home/stes/code/it4kids/src -I/usr/include/python2.7 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/5.2.0 -I/usr/include/c++/5.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include-fixed -I/usr/include src/dragelemcategory.h -o generated/moc_dragelemcategory.cpp

generated/moc_dragelemlist.cpp: src/dragableelement.h \
		src/scriptarea.h \
		src/scriptdock.h \
		src/dockingarea.h \
		src/dragelemlist.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/stes/code/it4kids -I/home/stes/code/it4kids/src -I/usr/include/python2.7 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/5.2.0 -I/usr/include/c++/5.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include-fixed -I/usr/include src/dragelemlist.h -o generated/moc_dragelemlist.cpp

generated/moc_scriptarea.cpp: src/scriptarea.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/stes/code/it4kids -I/home/stes/code/it4kids/src -I/usr/include/python2.7 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/5.2.0 -I/usr/include/c++/5.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include-fixed -I/usr/include src/scriptarea.h -o generated/moc_scriptarea.cpp

generated/moc_hatde.cpp: src/dragableelement.h \
		src/scriptarea.h \
		src/scriptdock.h \
		src/dockingarea.h \
		src/hatde.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/stes/code/it4kids -I/home/stes/code/it4kids/src -I/usr/include/python2.7 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/5.2.0 -I/usr/include/c++/5.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include-fixed -I/usr/include src/hatde.h -o generated/moc_hatde.cpp

generated/moc_commandde.cpp: src/dragableelement.h \
		src/scriptarea.h \
		src/scriptdock.h \
		src/dockingarea.h \
		src/commandde.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/stes/code/it4kids -I/home/stes/code/it4kids/src -I/usr/include/python2.7 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/5.2.0 -I/usr/include/c++/5.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include-fixed -I/usr/include src/commandde.h -o generated/moc_commandde.cpp

generated/moc_wrapperde.cpp: src/dragableelement.h \
		src/scriptarea.h \
		src/scriptdock.h \
		src/dockingarea.h \
		src/wrapperde.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/stes/code/it4kids -I/home/stes/code/it4kids/src -I/usr/include/python2.7 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/5.2.0 -I/usr/include/c++/5.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include-fixed -I/usr/include src/wrapperde.h -o generated/moc_wrapperde.cpp

generated/moc_predicatede.cpp: src/dragableelement.h \
		src/scriptarea.h \
		src/scriptdock.h \
		src/dockingarea.h \
		src/predicatede.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/stes/code/it4kids -I/home/stes/code/it4kids/src -I/usr/include/python2.7 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/5.2.0 -I/usr/include/c++/5.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include-fixed -I/usr/include src/predicatede.h -o generated/moc_predicatede.cpp

generated/moc_paramdock.cpp: src/dockingarea.h \
		src/param.h \
		src/paramdock.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/stes/code/it4kids -I/home/stes/code/it4kids/src -I/usr/include/python2.7 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/5.2.0 -I/usr/include/c++/5.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include-fixed -I/usr/include src/paramdock.h -o generated/moc_paramdock.cpp

generated/moc_paramnumber.cpp: src/param.h \
		src/paramnumber.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/stes/code/it4kids -I/home/stes/code/it4kids/src -I/usr/include/python2.7 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/5.2.0 -I/usr/include/c++/5.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include-fixed -I/usr/include src/paramnumber.h -o generated/moc_paramnumber.cpp

generated/moc_paramstring.cpp: src/param.h \
		src/paramstring.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/stes/code/it4kids -I/home/stes/code/it4kids/src -I/usr/include/python2.7 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/5.2.0 -I/usr/include/c++/5.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include-fixed -I/usr/include src/paramstring.h -o generated/moc_paramstring.cpp

generated/moc_paramdirection.cpp: src/param.h \
		src/paramdirection.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/stes/code/it4kids -I/home/stes/code/it4kids/src -I/usr/include/python2.7 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/5.2.0 -I/usr/include/c++/5.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include-fixed -I/usr/include src/paramdirection.h -o generated/moc_paramdirection.cpp

generated/moc_paramdestination.cpp: src/param.h \
		src/paramdestination.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/stes/code/it4kids -I/home/stes/code/it4kids/src -I/usr/include/python2.7 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/5.2.0 -I/usr/include/c++/5.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include-fixed -I/usr/include src/paramdestination.h -o generated/moc_paramdestination.cpp

generated/moc_paramkey.cpp: src/param.h \
		src/paramkey.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/stes/code/it4kids -I/home/stes/code/it4kids/src -I/usr/include/python2.7 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/5.2.0 -I/usr/include/c++/5.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include-fixed -I/usr/include src/paramkey.h -o generated/moc_paramkey.cpp

generated/moc_paraminteraction.cpp: src/param.h \
		src/paraminteraction.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/stes/code/it4kids -I/home/stes/code/it4kids/src -I/usr/include/python2.7 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/5.2.0 -I/usr/include/c++/5.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include-fixed -I/usr/include src/paraminteraction.h -o generated/moc_paraminteraction.cpp

generated/moc_parammessage.cpp: src/param.h \
		src/parammessage.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/stes/code/it4kids -I/home/stes/code/it4kids/src -I/usr/include/python2.7 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/5.2.0 -I/usr/include/c++/5.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include-fixed -I/usr/include src/parammessage.h -o generated/moc_parammessage.cpp

generated/moc_paramstopchoices.cpp: src/param.h \
		src/paramstopchoices.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/stes/code/it4kids -I/home/stes/code/it4kids/src -I/usr/include/python2.7 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/5.2.0 -I/usr/include/c++/5.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include-fixed -I/usr/include src/paramstopchoices.h -o generated/moc_paramstopchoices.cpp

generated/moc_paramclone.cpp: src/param.h \
		src/paramclone.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/stes/code/it4kids -I/home/stes/code/it4kids/src -I/usr/include/python2.7 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/5.2.0 -I/usr/include/c++/5.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include-fixed -I/usr/include src/paramclone.h -o generated/moc_paramclone.cpp

generated/moc_paramcostume.cpp: src/param.h \
		src/paramcostume.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/stes/code/it4kids -I/home/stes/code/it4kids/src -I/usr/include/python2.7 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/5.2.0 -I/usr/include/c++/5.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include-fixed -I/usr/include src/paramcostume.h -o generated/moc_paramcostume.cpp

generated/moc_parameffect.cpp: src/param.h \
		src/parameffect.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/stes/code/it4kids -I/home/stes/code/it4kids/src -I/usr/include/python2.7 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/5.2.0 -I/usr/include/c++/5.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include-fixed -I/usr/include src/parameffect.h -o generated/moc_parameffect.cpp

generated/moc_paramtouch.cpp: src/param.h \
		src/paramtouch.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/stes/code/it4kids -I/home/stes/code/it4kids/src -I/usr/include/python2.7 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/5.2.0 -I/usr/include/c++/5.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include-fixed -I/usr/include src/paramtouch.h -o generated/moc_paramtouch.cpp

generated/moc_paramcolor.cpp: src/param.h \
		src/paramcolor.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/stes/code/it4kids -I/home/stes/code/it4kids/src -I/usr/include/python2.7 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/5.2.0 -I/usr/include/c++/5.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include-fixed -I/usr/include src/paramcolor.h -o generated/moc_paramcolor.cpp

generated/moc_paramsound.cpp: src/param.h \
		src/paramsound.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/stes/code/it4kids -I/home/stes/code/it4kids/src -I/usr/include/python2.7 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/5.2.0 -I/usr/include/c++/5.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include-fixed -I/usr/include src/paramsound.h -o generated/moc_paramsound.cpp

generated/moc_reporterde.cpp: src/dragableelement.h \
		src/scriptarea.h \
		src/scriptdock.h \
		src/dockingarea.h \
		src/reporterde.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/stes/code/it4kids -I/home/stes/code/it4kids/src -I/usr/include/python2.7 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/5.2.0 -I/usr/include/c++/5.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include-fixed -I/usr/include src/reporterde.h -o generated/moc_reporterde.cpp

generated/moc_parammath.cpp: src/param.h \
		src/parammath.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/stes/code/it4kids -I/home/stes/code/it4kids/src -I/usr/include/python2.7 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/5.2.0 -I/usr/include/c++/5.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include-fixed -I/usr/include src/parammath.h -o generated/moc_parammath.cpp

generated/moc_paramjoinwords.cpp: src/param.h \
		src/paramstring.h \
		src/paramjoinwords.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/stes/code/it4kids -I/home/stes/code/it4kids/src -I/usr/include/python2.7 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/5.2.0 -I/usr/include/c++/5.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include-fixed -I/usr/include src/paramjoinwords.h -o generated/moc_paramjoinwords.cpp

generated/moc_paramtype.cpp: src/param.h \
		src/paramtype.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/stes/code/it4kids -I/home/stes/code/it4kids/src -I/usr/include/python2.7 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/5.2.0 -I/usr/include/c++/5.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include-fixed -I/usr/include src/paramtype.h -o generated/moc_paramtype.cpp

generated/moc_paramdelim.cpp: src/param.h \
		src/paramdelim.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/stes/code/it4kids -I/home/stes/code/it4kids/src -I/usr/include/python2.7 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/5.2.0 -I/usr/include/c++/5.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include-fixed -I/usr/include src/paramdelim.h -o generated/moc_paramdelim.cpp

generated/moc_paramvariables.cpp: src/param.h \
		src/paramvariables.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/stes/code/it4kids -I/home/stes/code/it4kids/src -I/usr/include/python2.7 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/5.2.0 -I/usr/include/c++/5.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include-fixed -I/usr/include src/paramvariables.h -o generated/moc_paramvariables.cpp

generated/moc_paramlistselec.cpp: src/param.h \
		src/paramlistselec.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/stes/code/it4kids -I/home/stes/code/it4kids/src -I/usr/include/python2.7 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/5.2.0 -I/usr/include/c++/5.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include-fixed -I/usr/include src/paramlistselec.h -o generated/moc_paramlistselec.cpp

generated/moc_paramlistid.cpp: src/param.h \
		src/paramlistid.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/stes/code/it4kids -I/home/stes/code/it4kids/src -I/usr/include/python2.7 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/5.2.0 -I/usr/include/c++/5.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include-fixed -I/usr/include src/paramlistid.h -o generated/moc_paramlistid.cpp

generated/moc_spriteselect.cpp: src/spriteselect.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/stes/code/it4kids -I/home/stes/code/it4kids/src -I/usr/include/python2.7 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/5.2.0 -I/usr/include/c++/5.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include-fixed -I/usr/include src/spriteselect.h -o generated/moc_spriteselect.cpp

generated/moc_sprite.cpp: src/sprite.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/stes/code/it4kids -I/home/stes/code/it4kids/src -I/usr/include/python2.7 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/5.2.0 -I/usr/include/c++/5.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include-fixed -I/usr/include src/sprite.h -o generated/moc_sprite.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: src/mainwindow.ui \
		src/scene.h \
		src/categoryselect.h \
		src/dragelemlist.h \
		src/scriptarea.h \
		src/spriteselect.h \
		src/dragelemcategory.h \
		src/mainwindow.h \
		src/dragableelement.h \
		src/scriptarea.h \
		src/scriptdock.h \
		src/dockingarea.h \
		src/dragelemlist.h \
		src/dragableelement.h \
		src/scriptarea.h \
		src/scriptdock.h \
		src/dockingarea.h
	/usr/lib/qt/bin/uic src/mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

generated/main.o: src/main.cpp src/mainwindow.h \
		src/sprite.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/main.o src/main.cpp

generated/mainwindow.o: src/mainwindow.cpp src/mainwindow.h \
		ui_mainwindow.h \
		src/categoryselect.h \
		src/dragelemcategory.h \
		src/dragableelement.h \
		src/scriptarea.h \
		src/scriptdock.h \
		src/dockingarea.h \
		src/dragelemlist.h \
		src/scene.h \
		src/spriteselect.h \
		src/commandde.h \
		src/hatde.h \
		src/sprite.h \
		src/wrapperde.h \
		src/predicatede.h \
		src/reporterde.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/mainwindow.o src/mainwindow.cpp

generated/scene.o: src/scene.cpp src/scene.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/scene.o src/scene.cpp

generated/categoryselect.o: src/categoryselect.cpp src/categoryselect.h \
		src/dragelemcategory.h \
		src/mainwindow.h \
		src/dragableelement.h \
		src/scriptarea.h \
		src/scriptdock.h \
		src/dockingarea.h \
		src/dragelemlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/categoryselect.o src/categoryselect.cpp

generated/dragableelement.o: src/dragableelement.cpp src/dragableelement.h \
		src/scriptarea.h \
		src/scriptdock.h \
		src/dockingarea.h \
		src/paramcolor.h \
		src/param.h \
		src/paramclone.h \
		src/paramcostume.h \
		src/paramdelim.h \
		src/paramdestination.h \
		src/paramdirection.h \
		src/paramdock.h \
		src/parameffect.h \
		src/paraminteraction.h \
		src/paramjoinwords.h \
		src/paramstring.h \
		src/paramkey.h \
		src/paramlistid.h \
		src/paramlistselec.h \
		src/parammath.h \
		src/parammessage.h \
		src/paramnumber.h \
		src/paramsound.h \
		src/paramstopchoices.h \
		src/paramtouch.h \
		src/paramtype.h \
		src/paramvariables.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/dragableelement.o src/dragableelement.cpp

generated/dragelemcategory.o: src/dragelemcategory.cpp src/dragelemcategory.h \
		src/mainwindow.h \
		src/dragableelement.h \
		src/scriptarea.h \
		src/scriptdock.h \
		src/dockingarea.h \
		src/dragelemlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/dragelemcategory.o src/dragelemcategory.cpp

generated/dragelemlist.o: src/dragelemlist.cpp src/dragelemlist.h \
		src/dragableelement.h \
		src/scriptarea.h \
		src/scriptdock.h \
		src/dockingarea.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/dragelemlist.o src/dragelemlist.cpp

generated/scriptarea.o: src/scriptarea.cpp src/scriptarea.h \
		src/dragableelement.h \
		src/scriptdock.h \
		src/dockingarea.h \
		src/sprite.h \
		src/mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/scriptarea.o src/scriptarea.cpp

generated/hatde.o: src/hatde.cpp src/hatde.h \
		src/dragableelement.h \
		src/scriptarea.h \
		src/scriptdock.h \
		src/dockingarea.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/hatde.o src/hatde.cpp

generated/commandde.o: src/commandde.cpp src/commandde.h \
		src/dragableelement.h \
		src/scriptarea.h \
		src/scriptdock.h \
		src/dockingarea.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/commandde.o src/commandde.cpp

generated/wrapperde.o: src/wrapperde.cpp src/wrapperde.h \
		src/dragableelement.h \
		src/scriptarea.h \
		src/scriptdock.h \
		src/dockingarea.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/wrapperde.o src/wrapperde.cpp

generated/predicatede.o: src/predicatede.cpp src/predicatede.h \
		src/dragableelement.h \
		src/scriptarea.h \
		src/scriptdock.h \
		src/dockingarea.h \
		src/paramdock.h \
		src/param.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/predicatede.o src/predicatede.cpp

generated/paramdock.o: src/paramdock.cpp src/paramdock.h \
		src/dockingarea.h \
		src/param.h \
		src/predicatede.h \
		src/dragableelement.h \
		src/scriptarea.h \
		src/scriptdock.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/paramdock.o src/paramdock.cpp

generated/paramnumber.o: src/paramnumber.cpp src/paramnumber.h \
		src/param.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/paramnumber.o src/paramnumber.cpp

generated/paramstring.o: src/paramstring.cpp src/paramstring.h \
		src/param.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/paramstring.o src/paramstring.cpp

generated/paramdirection.o: src/paramdirection.cpp src/paramdirection.h \
		src/param.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/paramdirection.o src/paramdirection.cpp

generated/paramdestination.o: src/paramdestination.cpp src/paramdestination.h \
		src/param.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/paramdestination.o src/paramdestination.cpp

generated/paramkey.o: src/paramkey.cpp src/paramkey.h \
		src/param.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/paramkey.o src/paramkey.cpp

generated/paraminteraction.o: src/paraminteraction.cpp src/paraminteraction.h \
		src/param.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/paraminteraction.o src/paraminteraction.cpp

generated/parammessage.o: src/parammessage.cpp src/parammessage.h \
		src/param.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/parammessage.o src/parammessage.cpp

generated/paramstopchoices.o: src/paramstopchoices.cpp src/paramstopchoices.h \
		src/param.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/paramstopchoices.o src/paramstopchoices.cpp

generated/paramclone.o: src/paramclone.cpp src/paramclone.h \
		src/param.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/paramclone.o src/paramclone.cpp

generated/paramcostume.o: src/paramcostume.cpp src/paramcostume.h \
		src/param.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/paramcostume.o src/paramcostume.cpp

generated/parameffect.o: src/parameffect.cpp src/parameffect.h \
		src/param.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/parameffect.o src/parameffect.cpp

generated/paramtouch.o: src/paramtouch.cpp src/paramtouch.h \
		src/param.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/paramtouch.o src/paramtouch.cpp

generated/paramcolor.o: src/paramcolor.cpp src/paramcolor.h \
		src/param.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/paramcolor.o src/paramcolor.cpp

generated/paramsound.o: src/paramsound.cpp src/paramsound.h \
		src/param.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/paramsound.o src/paramsound.cpp

generated/reporterde.o: src/reporterde.cpp src/reporterde.h \
		src/dragableelement.h \
		src/scriptarea.h \
		src/scriptdock.h \
		src/dockingarea.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/reporterde.o src/reporterde.cpp

generated/parammath.o: src/parammath.cpp src/parammath.h \
		src/param.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/parammath.o src/parammath.cpp

generated/paramjoinwords.o: src/paramjoinwords.cpp src/paramjoinwords.h \
		src/param.h \
		src/paramstring.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/paramjoinwords.o src/paramjoinwords.cpp

generated/paramtype.o: src/paramtype.cpp src/paramtype.h \
		src/param.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/paramtype.o src/paramtype.cpp

generated/paramdelim.o: src/paramdelim.cpp src/paramdelim.h \
		src/param.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/paramdelim.o src/paramdelim.cpp

generated/paramvariables.o: src/paramvariables.cpp src/paramvariables.h \
		src/param.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/paramvariables.o src/paramvariables.cpp

generated/paramlistselec.o: src/paramlistselec.cpp src/paramlistselec.h \
		src/param.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/paramlistselec.o src/paramlistselec.cpp

generated/paramlistid.o: src/paramlistid.cpp src/paramlistid.h \
		src/param.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/paramlistid.o src/paramlistid.cpp

generated/dockingarea.o: src/dockingarea.cpp src/dockingarea.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/dockingarea.o src/dockingarea.cpp

generated/scriptdock.o: src/scriptdock.cpp src/scriptdock.h \
		src/dockingarea.h \
		src/commandde.h \
		src/dragableelement.h \
		src/scriptarea.h \
		src/hatde.h \
		src/wrapperde.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/scriptdock.o src/scriptdock.cpp

generated/spriteselect.o: src/spriteselect.cpp src/spriteselect.h \
		src/sprite.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/spriteselect.o src/spriteselect.cpp

generated/sprite.o: src/sprite.cpp src/sprite.h \
		src/scriptarea.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/sprite.o src/sprite.cpp

generated/qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/qrc_resources.o qrc_resources.cpp

generated/moc_mainwindow.o: generated/moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/moc_mainwindow.o generated/moc_mainwindow.cpp

generated/moc_scene.o: generated/moc_scene.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/moc_scene.o generated/moc_scene.cpp

generated/moc_categoryselect.o: generated/moc_categoryselect.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/moc_categoryselect.o generated/moc_categoryselect.cpp

generated/moc_dragableelement.o: generated/moc_dragableelement.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/moc_dragableelement.o generated/moc_dragableelement.cpp

generated/moc_dragelemcategory.o: generated/moc_dragelemcategory.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/moc_dragelemcategory.o generated/moc_dragelemcategory.cpp

generated/moc_dragelemlist.o: generated/moc_dragelemlist.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/moc_dragelemlist.o generated/moc_dragelemlist.cpp

generated/moc_scriptarea.o: generated/moc_scriptarea.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/moc_scriptarea.o generated/moc_scriptarea.cpp

generated/moc_hatde.o: generated/moc_hatde.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/moc_hatde.o generated/moc_hatde.cpp

generated/moc_commandde.o: generated/moc_commandde.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/moc_commandde.o generated/moc_commandde.cpp

generated/moc_wrapperde.o: generated/moc_wrapperde.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/moc_wrapperde.o generated/moc_wrapperde.cpp

generated/moc_predicatede.o: generated/moc_predicatede.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/moc_predicatede.o generated/moc_predicatede.cpp

generated/moc_paramdock.o: generated/moc_paramdock.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/moc_paramdock.o generated/moc_paramdock.cpp

generated/moc_paramnumber.o: generated/moc_paramnumber.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/moc_paramnumber.o generated/moc_paramnumber.cpp

generated/moc_paramstring.o: generated/moc_paramstring.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/moc_paramstring.o generated/moc_paramstring.cpp

generated/moc_paramdirection.o: generated/moc_paramdirection.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/moc_paramdirection.o generated/moc_paramdirection.cpp

generated/moc_paramdestination.o: generated/moc_paramdestination.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/moc_paramdestination.o generated/moc_paramdestination.cpp

generated/moc_paramkey.o: generated/moc_paramkey.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/moc_paramkey.o generated/moc_paramkey.cpp

generated/moc_paraminteraction.o: generated/moc_paraminteraction.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/moc_paraminteraction.o generated/moc_paraminteraction.cpp

generated/moc_parammessage.o: generated/moc_parammessage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/moc_parammessage.o generated/moc_parammessage.cpp

generated/moc_paramstopchoices.o: generated/moc_paramstopchoices.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/moc_paramstopchoices.o generated/moc_paramstopchoices.cpp

generated/moc_paramclone.o: generated/moc_paramclone.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/moc_paramclone.o generated/moc_paramclone.cpp

generated/moc_paramcostume.o: generated/moc_paramcostume.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/moc_paramcostume.o generated/moc_paramcostume.cpp

generated/moc_parameffect.o: generated/moc_parameffect.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/moc_parameffect.o generated/moc_parameffect.cpp

generated/moc_paramtouch.o: generated/moc_paramtouch.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/moc_paramtouch.o generated/moc_paramtouch.cpp

generated/moc_paramcolor.o: generated/moc_paramcolor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/moc_paramcolor.o generated/moc_paramcolor.cpp

generated/moc_paramsound.o: generated/moc_paramsound.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/moc_paramsound.o generated/moc_paramsound.cpp

generated/moc_reporterde.o: generated/moc_reporterde.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/moc_reporterde.o generated/moc_reporterde.cpp

generated/moc_parammath.o: generated/moc_parammath.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/moc_parammath.o generated/moc_parammath.cpp

generated/moc_paramjoinwords.o: generated/moc_paramjoinwords.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/moc_paramjoinwords.o generated/moc_paramjoinwords.cpp

generated/moc_paramtype.o: generated/moc_paramtype.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/moc_paramtype.o generated/moc_paramtype.cpp

generated/moc_paramdelim.o: generated/moc_paramdelim.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/moc_paramdelim.o generated/moc_paramdelim.cpp

generated/moc_paramvariables.o: generated/moc_paramvariables.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/moc_paramvariables.o generated/moc_paramvariables.cpp

generated/moc_paramlistselec.o: generated/moc_paramlistselec.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/moc_paramlistselec.o generated/moc_paramlistselec.cpp

generated/moc_paramlistid.o: generated/moc_paramlistid.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/moc_paramlistid.o generated/moc_paramlistid.cpp

generated/moc_spriteselect.o: generated/moc_spriteselect.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/moc_spriteselect.o generated/moc_spriteselect.cpp

generated/moc_sprite.o: generated/moc_sprite.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/moc_sprite.o generated/moc_sprite.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

